<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gtsam2mrpt_serial</name>
  <version>0.1.0</version>
  <description>A C++ library offering a GTSAM ⇆ mrpt-serialization bridge.</description>

  <maintainer email="joseluisblancoc@gmail.com">Jose-Luis Blanco-Claraco</maintainer>
  <license>BSD</license>

  <url type="website">https://github.com/MRPT/gtsam2mrpt_serial</url>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>mola_common</depend>
  <depend>mrpt_libbase</depend>
  <depend>gtsam</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>